### PR TITLE
Migrate to v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
Hi, I've migrate to use v0.14 API.
Could you review this PR?

### CODE REVIEW

**Comment by toyama0919** [comment]
LGTM！

**Comment by cosmo0920** [comment]
@toyama0919 An Fluentd slack community user reported this plugin is unusable in v0.14.
How long does it take to merge this PR?

Thanks in advance,

**Comment by toyama0919** [comment]
Thanks.
if V0.12 ver need fix, maintain other branch.

**Comment by toyama0919** [comment]
released v0.1.0.

https://rubygems.org/gems/fluent-plugin-formatter_sprintf

**Pull request merged**
